/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { BColor } from "./BColor";

export class BColorFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): BColor {
    return new Contract(address, _abi, signerOrProvider) as BColor;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getColor",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
